name: NASA Project CI
on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:
    env:
      #      set the env vairable
      CI: true
    strategy:
      matrix:
        node-version: [ 14.x,16.x ]
    runs-on: ubuntu-latest
    steps:
      #     This action checks-out your repository under $GITHUB_WORKSPACE, so your workflow can access it.
      - uses: actions/checkout@v2
      - name: Use Nodejs version ${{matrix.node-version}}
        uses: actions/setup-node@v2
        #        set the node version
        with:
          node-version: ${{matrix.node-version}}
      - run: npm install
      #        build the frontend
      - run: npm run build --prefix client
      - run: npm test
#  deploy:
##    ensure build first ,then deploy
#    needs: build
